# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
    initrd.kernelModules = [ "amdgpu" ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7834d079-f28d-40ab-adae-aa9ce5a7e515";
    fsType = "ext4";
  };

  fileSystems."/HD" = {
    device = "/dev/disk/by-uuid/e8a0f5c8-4a6f-4deb-a279-6c8b3eff0b1b";
    fsType = "ext4";
  };

  fileSystems."/boot/EFI" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f60e76c0-2f0f-4720-b092-49af5a6cbaaa"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
