[LegalNotice]
Accepted=true

[BitTorrent]
Session\AddExtensionToIncompleteFiles=false
Session\AddTorrentPaused=false
Session\AnnounceToAllTiers=true
Session\AnnounceToAllTrackers=true
Session\BTProtocol=TCP
Session\CreateTorrentSubfolder=true
Session\DefaultSavePath=/data/torrents/complete/
Session\DisableAutoTMMByDefault=false
Session\Encryption=1
Session\GlobalDLSpeedLimit=0
Session\GlobalUPSpeedLimit=0
Session\MaxActiveDownloads=3
Session\MaxActiveTorrents=-1
Session\MaxActiveUploads=20
Session\MaxConnections=200
Session\MaxConnectionsPerTorrent=100
Session\MaxRatioAction=1
Session\MaxSeedingMinutes=10080
Session\MaxSeedingMinutesAction=1
Session\MaxUploads=20
Session\MaxUploadsPerTorrent=100
Session\Port=6881
Session\TempPath=/data/torrents/incomplete/
Session\TempPathEnabled=true

[Preferences]
Connection\PortForwardingEnabled=false
Connection\RandomizePort=false
Speed\LimitLAN=true
Speed\LimitUTP=true
WebUI\LocalHostAuth=false
WebUI\Port=8090
