[
  (import ./btop)
  (import ./daw-plugins)
  (import ./fastfetch)
  (import ./firefox)
  (import ./ghostty)
  (import ./mangohud)
  (import ./mpv)
  (import ./neovim)
  (import ./nixgl)
  (import ./obs-studio)
  (import ./obsidian)
  (import ./starship)
  (import ./vs-code)
  (import ./wallpaper-engine)
  (import ./wezterm)
  (import ./zed)
  (import ./zen-browser)
  (import ./zsh)
]
