#! /bin/sh

## Environment
export PATH=${PATH}:$HOME/.scripts
export PATH=${PATH}:$HOME/.config/bspwm

## Allow keyboard shortcuts
sxhkd &

## Monitor setup
numberOfScreens=12

i=0
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( numberOfScreens / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done

## Rules
bspc config border_width         2
bspc config window_gap           60

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config click_to_focus button1

bspc rule -a Nautilus state=floating
bspc rule -a feh state=floating
bspc rule -a discord desktop='^1'

## Colours
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources
## xrdb -merge $(shuf -n1 -e ~/.colours/*)
xrdb -merge $(~/.colours/violla)
paintee
# Only use the function above if the cache of paintee couldn't be found
if [ -e ~/.cache/paintee ]; then
	. ~/.cache/paintee
	else
	getcolors
fi
