#! /bin/sh

## Environment
export PATH=${PATH}:$HOME/.local/bin
export PATH=${PATH}:$HOME/.scripts
export PATH=${PATH}:$HOME/.config/bspwm

## Allow keyboard shortcuts
sxhkd &

## Monitor setup
numberOfScreens=12

i=0
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( numberOfScreens / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done

## Rules
bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config click_to_focus button1

bspc rule -a Nautilus state=floating
bspc rule -a feh state=floating

# Start notification system
popups

# Everything is ready, send notification
notify-send -u low "BSPWM" "Hello $USER, Your computer is ready to use."
