#!/usr/bin/env bash

# Query the connected monitor for supported resolutions
OUTPUT=$(xrandr -q | grep ' connected ' | cut -f 1 -d " ")
OPTIONS=$(xrandr -q | sed -n '/ connected /,/ disconnected /p' | sed '1d;$d')

# Check for best compatible resolutions
if echo "$OPTIONS" | grep -q "5120x1440"; then
  xrandr --output $OUTPUT --mode 5120x1440 --refresh 120
elif echo "$OPTIONS" | grep -q "3840x1440"; then
  xrandr --output $OUTPUT--mode 3840x1440
elif echo "$OPTIONS" | grep -q "3360x1440"; then
  xrandr --output $OUTPUT --mode 3360x1440
elif echo "$OPTIONS" | grep -q "2560x1440"; then
  xrandr --output $OUTPUT --mode 2560x1440
elif echo "$OPTIONS" | grep -q "1760x1440"; then
  xrandr --output $OUTPUT --mode 1760x1440
else
  xrandr --output DP-0 --mode 1920x1080
fi
