#!/bin/bash
set -e

# Spit out important info
broadcast() {
  echo $1
  notify-send -u low "Keybindings" "$1"
}

# Reset back to normal
reset() {
  setxkbmap -layout us
}

# Default config
default() {
  broadcast "Keybindings reset to defaults"
  reset
}

# OSRS config
osrs_mode() {
  broadcast "Keybindings set to OSRS mode"

  # Firstly reset
  reset

  # Map num keys to function keys
  xmodmap -e "keycode 10 = F1"
  xmodmap -e "keycode 11 = F2"
  xmodmap -e "keycode 12 = F3"
  xmodmap -e "keycode 13 = F4"
  xmodmap -e "keycode 14 = F5"

  # Map function keys to nums
  xmodmap -e "keycode 67 = 1"
  xmodmap -e "keycode 68 = 2"
  xmodmap -e "keycode 69 = 3"
  xmodmap -e "keycode 70 = 4"
  xmodmap -e "keycode 71 = 5"
}

# Change keybindings
case $1 in
  rs)     osrs_mode ;;
  osrs)   osrs_mode ;;
  *)      default ;;
esac
common
