#!/bin/bash
set -e

# Spit out important info
broadcast() {
  echo $1
  notify-send -u low "Keybindings" "$1"
}

# Reset back to normal
reset() {

  # We could use setxkbmap, but
  # we don't know whether we want
  # US or UK bindings

  # Undo OSRS changes
  xmodmap -e "keycode 10 = 1"
  xmodmap -e "keycode 11 = 2"
  xmodmap -e "keycode 12 = 3"
  xmodmap -e "keycode 13 = 4"
  xmodmap -e "keycode 14 = 5"
}

# Default config
default() {
  broadcast "Keybindings reset to defaults"
  reset
}

# OSRS config
osrs_mode() {
  broadcast "Keybindings set to OSRS mode"

  # Firstly reset
  reset

  # Map num keys to function keys
  xmodmap -e "keycode 10 = F1"
  xmodmap -e "keycode 11 = F2"
  xmodmap -e "keycode 12 = F3"
  xmodmap -e "keycode 13 = F4"
  xmodmap -e "keycode 14 = F5"
}

# Change keybindings
case $1 in
  rs)     osrs_mode ;;
  osrs)   osrs_mode ;;
  *)      default ;;
esac
common
