#!/bin/sh
GAMEPATH="$HOME/albiononline"
export LD_LIBRARY_PATH=/usr/lib
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins/platforms
export QT_PLUGIN_PATH=/usr/lib/qt/plugins
sed -i -e '/Screenmanager Resolution Height/d' "$HOME/.config/unity3d/Sandbox Interactive GmbH/Albion Online Client/prefs"
sed -i -e '/Screenmanager Resolution Width/d' "$HOME/.config/unity3d/Sandbox Interactive GmbH/Albion Online Client/prefs"

# Clean the directory
for file in $(ls -l "$GAMEPATH/launcher/" | grep -v "Albion-Online" | grep -v "launcher.log" | grep -v "version.txt")
do
if [ -f $GAMEPATH/launcher/${file} ]
then
echo "Removing launcher/${file}"
rm $GAMEPATH/launcher/${file}
fi
done

# Start Albion Online
LD_PRELOAD=/usr/lib/libSDL2-2.0.so.0 "$GAMEPATH/launcher/Albion-Online" 
