#!/bin/sh

# A simple script to take screenshoot using scrot
# Then add date to the file name
# Then open the result instantly using Viewnior

mkdir -p ~/Pictures/screenshots
sleep 0.2
scrot -s 'screenshot_%y.%m.%d_%H.%M.%S.png' \
-e 'mv $f ~/Pictures/screenshots/ ; xclip -selection c -t image/png -i ~/Pictures/screenshots/$f ; feh ~/Pictures/screenshots/$f'
