#!/bin/bash

# Launch dmenu with colours from XResources
dmenu \
  -nb $(xrdb -query | grep "dmenu.background" | cut -f 2) \
  -nf $(xrdb -query | grep "dmenu.foreground" | cut -f 2) \
  -sb $(xrdb -query | grep "dmenu.highlight-background" | cut -f 2) \
  -sf $(xrdb -query | grep "dmenu.highlight-foreground" | cut -f 2) \
  "$@"
  
