#!/bin/bash

# Launch rofi with custom configuration
rofi -show run -sidebar-mode \
-modi run,drun,window \
-terminal st \
-hide-scrollbar true \
-bw 2 \
-lines 12 \
-padding 24 \
-width 60 \
-location 0 \
-columns 4 \
-font "Noto Sans 10" \
-color-enabled true \
-color-window "$BACKGROUND,$BLACK,$BACKGROUND" \
-color-normal "$BACKGROUND,$FOREGROUND,$BACKGROUND,$BACKGROUND,$BLUE" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND,$BACKGROUND,$BLUE" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND,$BACKGROUND,$BLUE"
