#!/bin/sh

# Load xrandr customisation
$HOME/.screenlayout/default.sh

# Perform keybinding remappings
xmodmap $HOME/.config/xmodmap/xmodmap.conf

# Reload resources
xrdb $HOME/.Xresources

# Set background
$HOME/.fehbg

# Add any programs that should start before BSPWM here
mpd &
numlockx &
dropbox &
discord &

# Enable popups
$HOME/.scripts/popups

# Start music notifications
killall mpd-notification
mpd-notification -m $HOME/Music &

# Show polybar
$HOME/.scripts/start-poly
