#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar -c $HOME/.config/polybar/config.ini --reload main &
    echo $! > /tmp/polybar_pid_$m
  done
else
  polybar -c $HOME/.config/polybar/config.ini --reload main &
fi

# Tell terminal that polybar launched
echo "Bars launched..."
