#!/bin/bash

# Add any programs that should start before BSPWM here
$HOME/.fehbg &
mpd &
numlockx &
dropbox &
popups &

# These programs should load just as BSPWM is loading
sleep 2
discord &
popups &
mpd-notification -m ${HOME}/Music &

