#!/usr/bin/env bash

# Perform keybinding remappings
xmodmap $HOME/.config/xmodmap/xmodmap.conf

# Reload resources
xrdb $HOME/.Xresources

# Set background
$HOME/.fehbg

# Start order-insensitive programs
mpd &
numlockx &

# Autostart all executable files in autostart
for file in $HOME/.config/autostart/*; do
  dex "$file"
done

# Enable popups
$HOME/.scripts/popups
