#!/bin/bash
set -e

# Spit out important info
broadcast() {
  echo $1
  notify-send -u low "Tablet setup" "$1"
}

# Settings that are applied regardless
common() {
  # Force tablet to resize to primary monitor (hardcoded)
  local output="2560x1440+1920+0"
  xsetwacom set "Wacom Intuos PT S Pen stylus" MapToOutput ${output}
  echo "Tablet mapped to ${output}."

  # Turn off touch
  xsetwacom set "Wacom Intuos PT S Finger touch" touch off
  echo "Touch disabled."
}

# Default config
standard_mode() {
  broadcast "Tablet set to Standard mode."

  # Reset tablet area to full size
  xsetwacom set "Wacom Intuos PT S Pen stylus" ResetArea
}

# Osu only config
osu_mode() {
  broadcast "Tablet set to Osu mode."

  # Set area corners from (0,2287) to (5590,6509)
  xsetwacom set "Wacom Intuos PT S Pen stylus" Area 0 2287 5590 6509
}

# Change tablet mode depending on argument
case $1 in
  osu)  osu_mode ;;
  *)    standard_mode ;;
esac
common
