#!/bin/sh

# Prepare to send notifications
attempt=0
url="twitch.tv/$1"

# Open twitch in a new MPV window
dunstify -u low -r "$$" "Opening $url"
while ! mpv https://$url
do 
  attempt=$((attempt + 1))
  dunstify -u low -r "$$" "Opening $url" "Attempted $attempt times.."
done
